### PR TITLE
Add check for GCS file upload exist

### PR DESCRIPTION
**Pull request by chowbao**
<details>
  <summary>PR Checklist</summary>

### PR Structure

- [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
- [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
      otherwise).
- [ ] This PR's title starts with the jira ticket associated with the PR.

### Thoroughness

- [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
- [ ] I've updated the README with the added features, breaking changes, new instructions on how to use the repository. I updated the description of the fuction with the changes that were made.

### Release planning

- [ ] I've decided if this PR requires a new major/minor/patch version accordingly to
    [semver](https://semver.org/), and I've changed the name of the BRANCH to release/_ , feature/_ or patch/\* .
</details>

### What

Adding a check to see if the stellar-etl exported data file was actually upload and exists in GCS by checking for the file in GCS.

### Why

There have been times that the stellar-etl task in airflow has failed to upload a file to GCS and did not fail the task. This should prevent that scenario from happening again.

### Known limitations

It is in theory a redundant check but performance impact is negligible

### CODE REVIEW

**Comment by chowbao** [comment]
Need to test after logging issue is fixed in Airflow

**Review by amishas157 — APPROVED** [review]
This looks good. 
nit suggestion: To also verify size of the file is > 10b or something to ensure file is not empty

But defer to you whether that's really needed or not

**Comment by chowbao** [comment]
> This looks good. nit suggestion: To also verify size of the file is > 10b or something to ensure file is not empty
> 
> But defer to you whether that's really needed or not

Actually the files can be empty in the case there is no record for a time range 😅 
Example:
https://console.cloud.google.com/storage/browser/_details/us-central1-test-hubble-43c3e190-bucket/dag-exported/scheduled__2024-07-25T00:00:00%2B00:00/changes_folder/708319-708382-claimable_balances.txt;tab=live_object?project=test-hubble-319619

**Comment by amishas157** [comment]
> Actually the files can be empty in the case there is no record for a time range 😅

Alright, then i take my nit suggestion back

**Pull request merged**
