### PR TITLE
Add dust trades

### PR DESCRIPTION
**Pull request by sydneynotthecity**
### Overview

Liquidity Pools has a rounding mechanism that causes trade prices to slip when trading in small amounts. 
Since the final traded amount is the only reported amount, we would like to know when a trade amount has slipped.

### Changes

* Add `TradeType` int32, an ordinal field where 1 = orderbook trades and 2 = liquidity pool trades
* Add `RoundingSlippage` null.Int that represents the slippage amount of liquidity pool trades, in basis points
* Add `SellerIsExact` a boolean that represents if the seller amount is the exact representation of the amount (or if it is the slipped amount)
* Update unit tests to add new fields

Closes [GH#258](https://github.com/stellar/hubble/issues/258)

### CODE REVIEW

**Review by erika-sdf — COMMENTED** [review]
Looks good overall. Is it possible to add a test case for `tradeType = 2` and one where `roundingSlippage` is not empty?

**Comment by sydneynotthecity** [comment]
Yeah, I think that's a good idea. Let me see how hard that would be to add.

**Comment by sydneynotthecity** [comment]
I've added two new unit test cases to `trades`:
1. Liquidity pool trade that is a `PathPaymentStrictSend`. The rounding slippage is 0 and validates `TradeType`
2. Liquidity pool trade that is a `PathPaymentStrictReceive` of a super small amount. Rounding slippage is 100 due to trade size.

**Review by erika-sdf — APPROVED** [review]

**Review by erika-sdf — APPROVED** [review]
Thanks for adding more complete test coverage. Looks good!

**Pull request merged**
