### PR TITLE
export_ledger_entry_changes: Compact changes within each ledger, not he full ledger range

### PR DESCRIPTION
**Pull request by 2opremio**
This mimics what Horizon does.

Compacting all the changes within the full supplied ledger range
implied that all the changes of each ledger entry got summarized to a
single change.

Doing the compaction within each ledger still summarizes all the changes
which happened in the ledger, but its much more reasonable than applying it
to the full range.

For instance, for ledger range `38117104` to `38117167` before the changes in this PR, we get the following entries for liquidity pool `d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b900`:

```sh
$ ./stellar-etl --start-ledger 38117104 --end-ledger 38117167  --core-executable /Users/fons/stellar-core/src/stellar-core --core-config docker/stellar-core.cfg --output output.old export_ledger_entry_changes
[...]
$ jq  'select( .liquidity_pool_id == "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003")'  < output.old/38117104-38117167-liquidity_pools.txt
```
```json
{
  "asset_a_amount": 15.3128101,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 3268.6421826,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117157,
  "ledger_entry_change": 0,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 223.6067977,
  "trustline_count": 1,
  "type": "constant_product"
}
```

With the new code, we get two entries:

```json
{
  "asset_a_amount": 10,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 5000,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117145,
  "ledger_entry_change": 0,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 223.6067977,
  "trustline_count": 1,
  "type": "constant_product"
}
{
  "asset_a_amount": 15.3128101,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 3268.6421826,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117157,
  "ledger_entry_change": 1,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 223.6067977,
  "trustline_count": 1,
  "type": "constant_product"
}
```

Also note that, if we completely remove compaction, we get an extra entry (from a creation change in ledger `38117145` which otherwise gets compacted away):

```json
{
  "asset_a_amount": 0,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 0,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117145,
  "ledger_entry_change": 0,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 0,
  "trustline_count": 1,
  "type": "constant_product"
}
{
  "asset_a_amount": 10,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 5000,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117145,
  "ledger_entry_change": 1,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 223.6067977,
  "trustline_count": 1,
  "type": "constant_product"
}
{
  "asset_a_amount": 15.3128101,
  "asset_a_code": "",
  "asset_a_issuer": "",
  "asset_a_type": "native",
  "asset_b_amount": 3268.6421826,
  "asset_b_code": "DOGET",
  "asset_b_issuer": "GDOEVDDBU6OBWKL7VHDAOKD77UP4DKHQYKOKJJT5PR3WRDBTX35HUEUX",
  "asset_b_type": "credit_alphanum12",
  "deleted": false,
  "fee": 30,
  "last_modified_ledger": 38117157,
  "ledger_entry_change": 1,
  "liquidity_pool_id": "d57f3769f4f44aca602a6318a45fcc80e4c47d825a8ce8b8e590aafe8e9b9003",
  "pool_share_count": 223.6067977,
  "trustline_count": 1,
  "type": "constant_product"
}
```

If the behavior above is preferable, we can simply remove the compactor (but note that it will have a different behavior compared to Horizon and that the output will be larger).

### CODE REVIEW

**Comment by sydneynotthecity** [comment]
One downfall if we choose to remove the compactor is we do not have a clear way to order the ledger change entries. How would we know within the ledger sequence the order of operations? We could make some guesses with `history_transactions` and `history_operations` but it would be difficult. Would there be a way to determine order based on when the ledger entry change was read? or is order not guaranteed?

**Comment by 2opremio** [comment]
The metadata is passed in order by captive core. I guess we could add an extra ordering index.

**Comment by 2opremio** [comment]
How total ordering works is ledger sequence + transaction index within the ledger + operation index within the transaction, but I am not sure that's the best approach.

**Comment by sydneynotthecity** [comment]
History was originally not stored in the Hubble state tables, which is why the ledger changes were compacted across a range. This code was just going to produce a current snapshot of the state tables without saving history. Since we changed the design to save all states, it doesn't make sense for use to compact across a range (imo)

**Review by sydneynotthecity — APPROVED** [review]
LGTM, ready for merge

**Pull request merged**
